/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author JAOUEN
 */
public class VueCreerCompte extends javax.swing.JFrame {

    /**
     * Creates new form VueCreerCompte
     */
    public VueCreerCompte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCreerCompte = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jTextFieldPseudo = new javax.swing.JTextField();
        jLabelPseudo = new javax.swing.JLabel();
        jLabelMotDePasse = new javax.swing.JLabel();
        jButtonQuitter = new javax.swing.JButton();
        jButtonAccueil = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelEtatPseudo = new javax.swing.JLabel();
        jLabelEtatEmail = new javax.swing.JLabel();
        jLabelEtatMdp = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jCheckBoxAfficher = new javax.swing.JCheckBox();
        jButtonAfficher = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Creez votre compte");

        jPanelCreerCompte.setLayout(null);

        jLabelTitre.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(204, 0, 0));
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Creez votre compte");
        jPanelCreerCompte.add(jLabelTitre);
        jLabelTitre.setBounds(0, 0, 720, 50);

        jButtonValider.setText("Valider");
        jPanelCreerCompte.add(jButtonValider);
        jButtonValider.setBounds(250, 300, 65, 23);

        jTextFieldPseudo.setText("Pseudo");
        jTextFieldPseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPseudoActionPerformed(evt);
            }
        });
        jPanelCreerCompte.add(jTextFieldPseudo);
        jTextFieldPseudo.setBounds(230, 90, 270, 20);

        jLabelPseudo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelPseudo.setForeground(new java.awt.Color(0, 0, 204));
        jLabelPseudo.setText("Pseudo :");
        jPanelCreerCompte.add(jLabelPseudo);
        jLabelPseudo.setBounds(230, 50, 140, 30);

        jLabelMotDePasse.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelMotDePasse.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMotDePasse.setText("Mot de passe :");
        jPanelCreerCompte.add(jLabelMotDePasse);
        jLabelMotDePasse.setBounds(230, 120, 210, 30);

        jButtonQuitter.setText("Quitter");
        jPanelCreerCompte.add(jButtonQuitter);
        jButtonQuitter.setBounds(630, 500, 67, 23);

        jButtonAccueil.setText("Accueil");
        jPanelCreerCompte.add(jButtonAccueil);
        jButtonAccueil.setBounds(20, 500, 65, 23);

        jLabelEmail.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(0, 0, 204));
        jLabelEmail.setText("Email :");
        jPanelCreerCompte.add(jLabelEmail);
        jLabelEmail.setBounds(230, 180, 110, 30);

        jPasswordFieldPassword.setText("MotDePasse");
        jPasswordFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPasswordActionPerformed(evt);
            }
        });
        jPanelCreerCompte.add(jPasswordFieldPassword);
        jPasswordFieldPassword.setBounds(230, 150, 270, 20);

        jLabelEtatPseudo.setText("Etat Pseudo");
        jPanelCreerCompte.add(jLabelEtatPseudo);
        jLabelEtatPseudo.setBounds(520, 90, 58, 14);

        jLabelEtatEmail.setText("Etat email");
        jPanelCreerCompte.add(jLabelEtatEmail);
        jLabelEtatEmail.setBounds(520, 230, 47, 14);

        jLabelEtatMdp.setText("Etat Mdp");
        jPanelCreerCompte.add(jLabelEtatMdp);
        jLabelEtatMdp.setBounds(520, 150, 43, 14);

        jTextFieldEmail.setText("Email");
        jPanelCreerCompte.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(230, 220, 270, 20);
        jPanelCreerCompte.add(jCheckBoxAfficher);
        jCheckBoxAfficher.setBounds(570, 150, 20, 21);

        jButtonAfficher.setText("Afficher");
        jPanelCreerCompte.add(jButtonAfficher);
        jButtonAfficher.setBounds(600, 150, 90, 23);
        jPanelCreerCompte.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 720, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCreerCompte, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCreerCompte, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPseudoActionPerformed

    private void jPasswordFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueCreerCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueCreerCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueCreerCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueCreerCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueCreerCompte().setVisible(true);
            }
        });
    }

    public JButton getjButtonValider() {
        return jButtonValider;
    }

    public JLabel getjLabelBackground() {
        return jLabelBackground;
    }

    public JLabel getjLabelEmail() {
        return jLabelEmail;
    }

    public JLabel getjLabelMotDePasse() {
        return jLabelMotDePasse;
    }

    public JLabel getjLabelPseudo() {
        return jLabelPseudo;
    }

    public JLabel getjLabelTitre() {
        return jLabelTitre;
    }

    public JPanel getjPanelCreerCompte() {
        return jPanelCreerCompte;
    }

    public JPasswordField getjPasswordFieldPassword() {
        return jPasswordFieldPassword;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public JTextField getjTextFieldPseudo() {
        return jTextFieldPseudo;
    }

    public JButton getjButtonAccueil() {
        return jButtonAccueil;
    }

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public JButton getjButtonAfficher() {
        return jButtonAfficher;
    }

    public JCheckBox getjCheckBoxAfficher() {
        return jCheckBoxAfficher;
    }

    public JLabel getjLabelEtatEmail() {
        return jLabelEtatEmail;
    }

    public JLabel getjLabelEtatMdp() {
        return jLabelEtatMdp;
    }

    public JLabel getjLabelEtatPseudo() {
        return jLabelEtatPseudo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JCheckBox jCheckBoxAfficher;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEtatEmail;
    private javax.swing.JLabel jLabelEtatMdp;
    private javax.swing.JLabel jLabelEtatPseudo;
    private javax.swing.JLabel jLabelMotDePasse;
    private javax.swing.JLabel jLabelPseudo;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanelCreerCompte;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldPseudo;
    // End of variables declaration//GEN-END:variables
}
