/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Benoit
 */
public class VueCapitalQuiz extends javax.swing.JFrame {

    /**
     * Creates new form VueCapitalQuiz
     */
    public VueCapitalQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCapital = new javax.swing.JPanel();
        jButtonCapitale1 = new javax.swing.JButton();
        jTextFieldReponseCash = new javax.swing.JTextField();
        jLabelVerdict = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jLabelPays = new javax.swing.JLabel();
        jProgressBarTime = new javax.swing.JProgressBar();
        jButtonCapitale2 = new javax.swing.JButton();
        jButtonCapitale3 = new javax.swing.JButton();
        jButtonCapitale4 = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jLabelClassement = new javax.swing.JLabel();
        jButtonMenu = new javax.swing.JButton();
        jButtonRejouer = new javax.swing.JButton();
        jLabelDrapeau = new javax.swing.JLabel();
        jLabelReponse = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jScrollPaneClassement = new javax.swing.JScrollPane();
        jTableScores = new javax.swing.JTable();
        jLabelJoueur = new javax.swing.JLabel();
        jLabelCountdown = new javax.swing.JLabel();
        jButtonRecommencer = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz capitale");
        setResizable(false);

        jPanelCapital.setLayout(null);

        jButtonCapitale1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jButtonCapitale1.setText("Capitale 1");
        jPanelCapital.add(jButtonCapitale1);
        jButtonCapitale1.setBounds(110, 220, 230, 60);
        jPanelCapital.add(jTextFieldReponseCash);
        jTextFieldReponseCash.setBounds(220, 280, 290, 20);

        jLabelVerdict.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabelVerdict.setForeground(new java.awt.Color(255, 0, 0));
        jLabelVerdict.setText("Perdu");
        jPanelCapital.add(jLabelVerdict);
        jLabelVerdict.setBounds(10, 30, 690, 17);

        jButtonOk.setText("OK");
        jPanelCapital.add(jButtonOk);
        jButtonOk.setBounds(520, 280, 47, 23);

        jLabelPays.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabelPays.setForeground(new java.awt.Color(51, 51, 255));
        jLabelPays.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPays.setText("Republique democratique du congo");
        jPanelCapital.add(jLabelPays);
        jLabelPays.setBounds(10, 140, 700, 40);
        jPanelCapital.add(jProgressBarTime);
        jProgressBarTime.setBounds(190, 410, 360, 20);

        jButtonCapitale2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jButtonCapitale2.setText("Capitale 2");
        jButtonCapitale2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapitale2ActionPerformed(evt);
            }
        });
        jPanelCapital.add(jButtonCapitale2);
        jButtonCapitale2.setBounds(380, 220, 230, 60);

        jButtonCapitale3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jButtonCapitale3.setText("Capitale 3");
        jPanelCapital.add(jButtonCapitale3);
        jButtonCapitale3.setBounds(110, 310, 230, 60);

        jButtonCapitale4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jButtonCapitale4.setText("Capitale 4");
        jPanelCapital.add(jButtonCapitale4);
        jButtonCapitale4.setBounds(380, 310, 230, 60);

        jButtonQuitter.setText("Quitter");
        jPanelCapital.add(jButtonQuitter);
        jButtonQuitter.setBounds(610, 440, 67, 23);

        jLabelClassement.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelClassement.setForeground(new java.awt.Color(0, 0, 204));
        jLabelClassement.setText("Classement");
        jPanelCapital.add(jLabelClassement);
        jLabelClassement.setBounds(10, 50, 690, 30);

        jButtonMenu.setText("Menu Principal");
        jPanelCapital.add(jButtonMenu);
        jButtonMenu.setBounds(10, 440, 101, 23);

        jButtonRejouer.setText("Rejouer");
        jPanelCapital.add(jButtonRejouer);
        jButtonRejouer.setBounds(310, 100, 100, 50);

        jLabelDrapeau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDrapeau.setText("Drapeau");
        jLabelDrapeau.setOpaque(true);
        jPanelCapital.add(jLabelDrapeau);
        jLabelDrapeau.setBounds(250, 10, 60, 40);

        jLabelReponse.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabelReponse.setForeground(new java.awt.Color(255, 0, 51));
        jLabelReponse.setText("Reponse");
        jPanelCapital.add(jLabelReponse);
        jLabelReponse.setBounds(150, 430, 530, 44);

        jLabelTime.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTime.setText("temps");
        jPanelCapital.add(jLabelTime);
        jLabelTime.setBounds(520, 70, 220, 44);

        jLabelScore.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabelScore.setForeground(new java.awt.Color(0, 204, 51));
        jLabelScore.setText("Score");
        jPanelCapital.add(jLabelScore);
        jLabelScore.setBounds(570, 10, 165, 58);

        jTableScores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneClassement.setViewportView(jTableScores);

        jPanelCapital.add(jScrollPaneClassement);
        jScrollPaneClassement.setBounds(140, 160, 452, 260);

        jLabelJoueur.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabelJoueur.setForeground(new java.awt.Color(102, 0, 102));
        jLabelJoueur.setText("Joueur");
        jPanelCapital.add(jLabelJoueur);
        jLabelJoueur.setBounds(10, 10, 470, 17);

        jLabelCountdown.setFont(new java.awt.Font("Perpetua Titling MT", 1, 100)); // NOI18N
        jLabelCountdown.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCountdown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCountdown.setText("Decompte");
        jPanelCapital.add(jLabelCountdown);
        jLabelCountdown.setBounds(-6, 4, 710, 480);

        jButtonRecommencer.setText("Recommencer");
        jPanelCapital.add(jButtonRecommencer);
        jButtonRecommencer.setBounds(10, 410, 100, 23);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_capitales.jpg"))); // NOI18N
        jPanelCapital.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 700, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCapital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCapital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCapitale2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapitale2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCapitale2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueCapitalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueCapitalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueCapitalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueCapitalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueCapitalQuiz().setVisible(true);
            }
        });
    }

    public JProgressBar getjProgressBarTime() {
        return jProgressBarTime;
    }

    public JButton getjButtonMenu() {
        return jButtonMenu;
    }

    public JButton getjButtonCapitale1() {
        return jButtonCapitale1;
    }

    public JButton getjButtonCapitale2() {
        return jButtonCapitale2;
    }

    public JButton getjButtonCapitale3() {
        return jButtonCapitale3;
    }

    public JButton getjButtonCapitale4() {
        return jButtonCapitale4;
    }

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public JLabel getjLabelPays() {
        return jLabelPays;
    }

    public JLabel getjLabelScore() {
        return jLabelScore;
    }

    public JButton getjButtonRejouer() {
        return jButtonRejouer;
    }

    public JLabel getjLabelVerdict() {
        return jLabelVerdict;
    }

    public JLabel getjLabelReponse() {
        return jLabelReponse;
    }

    public JLabel getjLabelTime() {
        return jLabelTime;
    }

    public JLabel getjLabelBackground() {
        return jLabelBackground;
    }

    public JTable getjTableScores() {
        return jTableScores;
    }

    public JScrollPane getjScrollPaneClassement() {
        return jScrollPaneClassement;
    }

    public JLabel getjLabelJoueur() {
        return jLabelJoueur;
    }


    public JLabel getjLabelDrapeau() {
        return jLabelDrapeau;
    }

    public JPanel getjPanelCapital() {
        return jPanelCapital;
    }

    public JLabel getjLabelClassement() {
        return jLabelClassement;
    }

    public JButton getjButtonRecommencer() {
        return jButtonRecommencer;
    }

    public JLabel getjLabelCountdown() {
        return jLabelCountdown;
    }

    public JButton getjButtonOk() {
        return jButtonOk;
    }

    public JTextField getjTextFieldReponseCash() {
        return jTextFieldReponseCash;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCapitale1;
    private javax.swing.JButton jButtonCapitale2;
    private javax.swing.JButton jButtonCapitale3;
    private javax.swing.JButton jButtonCapitale4;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRecommencer;
    private javax.swing.JButton jButtonRejouer;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelClassement;
    private javax.swing.JLabel jLabelCountdown;
    private javax.swing.JLabel jLabelDrapeau;
    private javax.swing.JLabel jLabelJoueur;
    private javax.swing.JLabel jLabelPays;
    private javax.swing.JLabel jLabelReponse;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelVerdict;
    private javax.swing.JPanel jPanelCapital;
    private javax.swing.JProgressBar jProgressBarTime;
    private javax.swing.JScrollPane jScrollPaneClassement;
    private javax.swing.JTable jTableScores;
    private javax.swing.JTextField jTextFieldReponseCash;
    // End of variables declaration//GEN-END:variables
}
