/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author lucas
 */
public class VueGestion extends javax.swing.JFrame {

    /**
     * Creates new form VueProfesseur
     */
    public VueGestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jButtonQuitter = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jLabelSouhait = new javax.swing.JLabel();
        jRadioButtonChoixEleve = new javax.swing.JRadioButton();
        jRadioButtonChoixScore = new javax.swing.JRadioButton();
        jComboBoxSupEleve = new javax.swing.JComboBox();
        jButtonSupEleve = new javax.swing.JButton();
        jLabelExplication1 = new javax.swing.JLabel();
        jLabelExplication2 = new javax.swing.JLabel();
        jLabelExplication6 = new javax.swing.JLabel();
        jLabelExplication5 = new javax.swing.JLabel();
        jLabelExplication3 = new javax.swing.JLabel();
        jLabelExplication4 = new javax.swing.JLabel();
        jRadioButtonSupScoreEleve = new javax.swing.JRadioButton();
        jComboBoxSupScoreEleve = new javax.swing.JComboBox();
        jRadioButtonSupScoreTheme = new javax.swing.JRadioButton();
        jComboBoxSupScoreTheme = new javax.swing.JComboBox();
        jRadioButtonSupScoreMode = new javax.swing.JRadioButton();
        jComboBoxSupScoreMode = new javax.swing.JComboBox();
        jRadioButtonSupScoreDifficulty = new javax.swing.JRadioButton();
        jComboBoxSupScoreDifficulty = new javax.swing.JComboBox();
        jButtonSupScore = new javax.swing.JButton();
        jLabelResult = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitre.setText("Bienvenue dans l'interface De Gestion de la Base de Données");
        jPanel1.add(jLabelTitre);
        jLabelTitre.setBounds(140, 20, 483, 22);

        jButtonQuitter.setText("Quitter");
        jPanel1.add(jButtonQuitter);
        jButtonQuitter.setBounds(620, 400, 90, 23);

        jButtonRetour.setText("Retour");
        jPanel1.add(jButtonRetour);
        jButtonRetour.setBounds(470, 400, 120, 23);

        jLabelSouhait.setText("Vous souhaitez :");
        jPanel1.add(jLabelSouhait);
        jLabelSouhait.setBounds(30, 54, 190, 20);

        jRadioButtonChoixEleve.setText("Supprimer un élève et ses scores de la base de données");
        jRadioButtonChoixEleve.setOpaque(false);
        jPanel1.add(jRadioButtonChoixEleve);
        jRadioButtonChoixEleve.setBounds(30, 80, 390, 23);

        jRadioButtonChoixScore.setText("Supprimer des scores de la base de donnée");
        jRadioButtonChoixScore.setOpaque(false);
        jPanel1.add(jRadioButtonChoixScore);
        jRadioButtonChoixScore.setBounds(30, 110, 310, 23);

        jComboBoxSupEleve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxSupEleve);
        jComboBoxSupEleve.setBounds(430, 70, 240, 30);

        jButtonSupEleve.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSupEleve.setText("Supprimer l'Elève");
        jButtonSupEleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupEleveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSupEleve);
        jButtonSupEleve.setBounds(410, 110, 290, 30);

        jLabelExplication1.setText("Plusieurs combinaisons possibles - Exemples :");
        jPanel1.add(jLabelExplication1);
        jLabelExplication1.setBounds(20, 140, 740, 14);

        jLabelExplication2.setText("Mode -> supprimera les scores de tout les élèves dans tout thème pour tel mode pour toute difficulté");
        jPanel1.add(jLabelExplication2);
        jLabelExplication2.setBounds(110, 180, 650, 14);

        jLabelExplication6.setText("Difficulté -> supprimera les scores de tout les élèves dans tout thème pour tout mode pour telle difficulté");
        jPanel1.add(jLabelExplication6);
        jLabelExplication6.setBounds(110, 200, 650, 14);

        jLabelExplication5.setText("Thème -> supprimera les scores de tout les élèves dans tout thème pour tout mode pour toute difficulté");
        jPanel1.add(jLabelExplication5);
        jLabelExplication5.setBounds(110, 160, 650, 14);

        jLabelExplication3.setText("Thème +  Difficulté -> supprimera les scores de tout les élèves dans tel thème pour tout mode pour telle difficulté");
        jPanel1.add(jLabelExplication3);
        jLabelExplication3.setBounds(110, 220, 650, 14);

        jLabelExplication4.setText("Eleve + Mode + Difficulté  -> supprimera les scores de l'élève dans tel mode pour telle difficulté");
        jPanel1.add(jLabelExplication4);
        jLabelExplication4.setBounds(110, 240, 740, 14);

        jRadioButtonSupScoreEleve.setText("D'un élève");
        jRadioButtonSupScoreEleve.setOpaque(false);
        jPanel1.add(jRadioButtonSupScoreEleve);
        jRadioButtonSupScoreEleve.setBounds(70, 260, 130, 23);

        jComboBoxSupScoreEleve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxSupScoreEleve);
        jComboBoxSupScoreEleve.setBounds(60, 290, 120, 30);

        jRadioButtonSupScoreTheme.setText("D'un Thème");
        jRadioButtonSupScoreTheme.setOpaque(false);
        jRadioButtonSupScoreTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSupScoreThemeActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonSupScoreTheme);
        jRadioButtonSupScoreTheme.setBounds(230, 260, 140, 23);

        jComboBoxSupScoreTheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxSupScoreTheme);
        jComboBoxSupScoreTheme.setBounds(220, 290, 120, 30);

        jRadioButtonSupScoreMode.setText("D'un Mode");
        jRadioButtonSupScoreMode.setOpaque(false);
        jPanel1.add(jRadioButtonSupScoreMode);
        jRadioButtonSupScoreMode.setBounds(410, 260, 150, 23);

        jComboBoxSupScoreMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxSupScoreMode);
        jComboBoxSupScoreMode.setBounds(400, 290, 120, 30);

        jRadioButtonSupScoreDifficulty.setText("D'une Diffculté");
        jRadioButtonSupScoreDifficulty.setOpaque(false);
        jPanel1.add(jRadioButtonSupScoreDifficulty);
        jRadioButtonSupScoreDifficulty.setBounds(570, 260, 120, 23);

        jComboBoxSupScoreDifficulty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxSupScoreDifficulty);
        jComboBoxSupScoreDifficulty.setBounds(570, 290, 120, 30);

        jButtonSupScore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSupScore.setText("Supprimer les Scores");
        jButtonSupScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupScoreActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSupScore);
        jButtonSupScore.setBounds(240, 340, 290, 30);

        jLabelResult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResult.setText("Scores supprimés de la base de données");
        jPanel1.add(jLabelResult);
        jLabelResult.setBounds(20, 380, 410, 40);
        jPanel1.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 740, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSupEleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupEleveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSupEleveActionPerformed

    private void jButtonSupScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSupScoreActionPerformed

    private void jRadioButtonSupScoreThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSupScoreThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSupScoreThemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGestion().setVisible(true);
            }
        });
    }

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public JButton getjButtonRetour() {
        return jButtonRetour;
    }

    public JButton getjButtonSupEleve() {
        return jButtonSupEleve;
    }

    public JButton getjButtonSupScore() {
        return jButtonSupScore;
    }

    public JComboBox getjComboBoxSupEleve() {
        return jComboBoxSupEleve;
    }

    public JComboBox getjComboBoxSupScoreDifficulty() {
        return jComboBoxSupScoreDifficulty;
    }

    public JComboBox getjComboBoxSupScoreEleve() {
        return jComboBoxSupScoreEleve;
    }

    public JComboBox getjComboBoxSupScoreMode() {
        return jComboBoxSupScoreMode;
    }

    public JComboBox getjComboBoxSupScoreTheme() {
        return jComboBoxSupScoreTheme;
    }

    public JLabel getjLabelBackground() {
        return jLabelBackground;
    }

    public JLabel getjLabelExplication1() {
        return jLabelExplication1;
    }

    public JLabel getjLabelExplication2() {
        return jLabelExplication2;
    }

    public JLabel getjLabelExplication3() {
        return jLabelExplication3;
    }

    public JLabel getjLabelExplication4() {
        return jLabelExplication4;
    }

    public JLabel getjLabelExplication5() {
        return jLabelExplication5;
    }

    public JLabel getjLabelExplication6() {
        return jLabelExplication6;
    }

    public JLabel getjLabelResult() {
        return jLabelResult;
    }

    public JLabel getjLabelSouhait() {
        return jLabelSouhait;
    }

    public JLabel getjLabelTitre() {
        return jLabelTitre;
    }

 

    public JRadioButton getjRadioButtonChoixEleve() {
        return jRadioButtonChoixEleve;
    }

    public JRadioButton getjRadioButtonChoixScore() {
        return jRadioButtonChoixScore;
    }

    public JRadioButton getjRadioButtonSupScoreDifficulty() {
        return jRadioButtonSupScoreDifficulty;
    }

    public JRadioButton getjRadioButtonSupScoreEleve() {
        return jRadioButtonSupScoreEleve;
    }

    public JRadioButton getjRadioButtonSupScoreMode() {
        return jRadioButtonSupScoreMode;
    }

    public JRadioButton getjRadioButtonSupScoreTheme() {
        return jRadioButtonSupScoreTheme;
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonSupEleve;
    private javax.swing.JButton jButtonSupScore;
    private javax.swing.JComboBox jComboBoxSupEleve;
    private javax.swing.JComboBox jComboBoxSupScoreDifficulty;
    private javax.swing.JComboBox jComboBoxSupScoreEleve;
    private javax.swing.JComboBox jComboBoxSupScoreMode;
    private javax.swing.JComboBox jComboBoxSupScoreTheme;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelExplication1;
    private javax.swing.JLabel jLabelExplication2;
    private javax.swing.JLabel jLabelExplication3;
    private javax.swing.JLabel jLabelExplication4;
    private javax.swing.JLabel jLabelExplication5;
    private javax.swing.JLabel jLabelExplication6;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelSouhait;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonChoixEleve;
    private javax.swing.JRadioButton jRadioButtonChoixScore;
    private javax.swing.JRadioButton jRadioButtonSupScoreDifficulty;
    private javax.swing.JRadioButton jRadioButtonSupScoreEleve;
    private javax.swing.JRadioButton jRadioButtonSupScoreMode;
    private javax.swing.JRadioButton jRadioButtonSupScoreTheme;
    // End of variables declaration//GEN-END:variables
}
