/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Benoit
 */
public class VueMenuChoix extends javax.swing.JFrame {

    /**
     * Creates new form VueMenuChoix
     */
    public VueMenuChoix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelChoixMenu = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jRadioButtonLieux = new javax.swing.JRadioButton();
        jRadioButtonCapitale = new javax.swing.JRadioButton();
        jRadioButtonSuperficie = new javax.swing.JRadioButton();
        jRadioButtonPopulation = new javax.swing.JRadioButton();
        jRadioButtonLangues = new javax.swing.JRadioButton();
        jRadioButtonContinent = new javax.swing.JRadioButton();
        jRadioButtonLocalisation = new javax.swing.JRadioButton();
        jRadioButtonDrapeau = new javax.swing.JRadioButton();
        jLabelMode = new javax.swing.JLabel();
        jLabelTheme = new javax.swing.JLabel();
        jButtonFacile = new javax.swing.JButton();
        jButtonMoyen = new javax.swing.JButton();
        jButtonDifficile = new javax.swing.JButton();
        jButtonExpert = new javax.swing.JButton();
        jButtonOptions = new javax.swing.JButton();
        jLabelDifficulte = new javax.swing.JLabel();
        jRadioButtonFormes = new javax.swing.JRadioButton();
        jRadioButtonClassique = new javax.swing.JRadioButton();
        jRadioButtonRapidite = new javax.swing.JRadioButton();
        jRadioButtonSurvie = new javax.swing.JRadioButton();
        jCheckBoxInverse = new javax.swing.JCheckBox();
        jLabelContinent = new javax.swing.JLabel();
        jButtonStandard = new javax.swing.JButton();
        jCheckBoxEurope = new javax.swing.JCheckBox();
        jCheckBoxAmeriqueDuNord = new javax.swing.JCheckBox();
        jCheckBoxAmeriqueDuSud = new javax.swing.JCheckBox();
        jCheckBoxAsie = new javax.swing.JCheckBox();
        jCheckBoxAfrique = new javax.swing.JCheckBox();
        jCheckBoxOceanie = new javax.swing.JCheckBox();
        jCheckBonus = new javax.swing.JCheckBox();
        jCheckBoxAntartique = new javax.swing.JCheckBox();
        jRadioButtonContreLaMontre = new javax.swing.JRadioButton();
        jRadioButtonDuo = new javax.swing.JRadioButton();
        jRadioButtonCarre = new javax.swing.JRadioButton();
        jRadioButtonCash = new javax.swing.JRadioButton();
        jRadioButtonEntrainement = new javax.swing.JRadioButton();
        jLabelModeReponse = new javax.swing.JLabel();
        jRadioButtonCompetition = new javax.swing.JRadioButton();
        jButtonFeedback = new javax.swing.JButton();
        jButtonCroissante = new javax.swing.JButton();
        jButtonImpossible = new javax.swing.JButton();
        jButtonBestScores = new javax.swing.JButton();
        jButtonSimilaire = new javax.swing.JButton();
        jRadioButtonSprint = new javax.swing.JRadioButton();
        jButtonDeconnexion = new javax.swing.JButton();
        jRadioButtonMonde = new javax.swing.JRadioButton();
        jButtonUltra = new javax.swing.JButton();
        jButtonProfil = new javax.swing.JButton();
        jButtonPiege = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jButtonSubtile = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Faites votre choix");

        jPanelChoixMenu.setLayout(null);

        jLabelTitre.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTitre.setText("Faites votre choix");
        jPanelChoixMenu.add(jLabelTitre);
        jLabelTitre.setBounds(350, 10, 230, 30);

        jRadioButtonLieux.setText("Lieux");
        jPanelChoixMenu.add(jRadioButtonLieux);
        jRadioButtonLieux.setBounds(550, 100, 110, 23);

        jRadioButtonCapitale.setText("Capitales");
        jPanelChoixMenu.add(jRadioButtonCapitale);
        jRadioButtonCapitale.setBounds(260, 100, 140, 23);

        jRadioButtonSuperficie.setText("Superficie");
        jPanelChoixMenu.add(jRadioButtonSuperficie);
        jRadioButtonSuperficie.setBounds(260, 140, 140, 23);

        jRadioButtonPopulation.setText("Population");
        jPanelChoixMenu.add(jRadioButtonPopulation);
        jRadioButtonPopulation.setBounds(410, 140, 110, 23);

        jRadioButtonLangues.setText("Langues");
        jPanelChoixMenu.add(jRadioButtonLangues);
        jRadioButtonLangues.setBounds(550, 140, 110, 23);

        jRadioButtonContinent.setText("Continent");
        jPanelChoixMenu.add(jRadioButtonContinent);
        jRadioButtonContinent.setBounds(260, 180, 100, 23);

        jRadioButtonLocalisation.setText("Localisation");
        jPanelChoixMenu.add(jRadioButtonLocalisation);
        jRadioButtonLocalisation.setBounds(410, 180, 110, 23);

        jRadioButtonDrapeau.setText("Drapeaux");
        jPanelChoixMenu.add(jRadioButtonDrapeau);
        jRadioButtonDrapeau.setBounds(410, 100, 110, 23);

        jLabelMode.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabelMode.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMode.setText("Mode");
        jPanelChoixMenu.add(jLabelMode);
        jLabelMode.setBounds(420, 220, 70, 30);

        jLabelTheme.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabelTheme.setForeground(new java.awt.Color(0, 204, 51));
        jLabelTheme.setText("Thème");
        jPanelChoixMenu.add(jLabelTheme);
        jLabelTheme.setBounds(420, 74, 100, 20);

        jButtonFacile.setText("Facile");
        jPanelChoixMenu.add(jButtonFacile);
        jButtonFacile.setBounds(160, 320, 90, 23);

        jButtonMoyen.setText("Moyen");
        jPanelChoixMenu.add(jButtonMoyen);
        jButtonMoyen.setBounds(270, 320, 110, 23);

        jButtonDifficile.setText("Difficile");
        jPanelChoixMenu.add(jButtonDifficile);
        jButtonDifficile.setBounds(390, 320, 90, 23);

        jButtonExpert.setText("Expert");
        jPanelChoixMenu.add(jButtonExpert);
        jButtonExpert.setBounds(500, 320, 100, 23);

        jButtonOptions.setText("Options");
        jPanelChoixMenu.add(jButtonOptions);
        jButtonOptions.setBounds(10, 10, 140, 23);

        jLabelDifficulte.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabelDifficulte.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDifficulte.setText("Difficulté");
        jPanelChoixMenu.add(jLabelDifficulte);
        jLabelDifficulte.setBounds(410, 290, 130, 30);

        jRadioButtonFormes.setText("Formes");
        jPanelChoixMenu.add(jRadioButtonFormes);
        jRadioButtonFormes.setBounds(550, 180, 93, 23);

        jRadioButtonClassique.setText("Classique");
        jPanelChoixMenu.add(jRadioButtonClassique);
        jRadioButtonClassique.setBounds(180, 250, 110, 23);

        jRadioButtonRapidite.setText("Rapidité");
        jPanelChoixMenu.add(jRadioButtonRapidite);
        jRadioButtonRapidite.setBounds(460, 250, 100, 23);

        jRadioButtonSurvie.setText("Survie");
        jPanelChoixMenu.add(jRadioButtonSurvie);
        jRadioButtonSurvie.setBounds(600, 250, 90, 23);

        jCheckBoxInverse.setText("Mode inverse");
        jPanelChoixMenu.add(jCheckBoxInverse);
        jCheckBoxInverse.setBounds(570, 390, 130, 30);

        jLabelContinent.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabelContinent.setForeground(new java.awt.Color(0, 0, 204));
        jLabelContinent.setText("Continent");
        jPanelChoixMenu.add(jLabelContinent);
        jLabelContinent.setBounds(420, 470, 90, 40);

        jButtonStandard.setText("Standard");
        jPanelChoixMenu.add(jButtonStandard);
        jButtonStandard.setBounds(210, 360, 90, 23);

        jCheckBoxEurope.setText("Europe");
        jCheckBoxEurope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEuropeActionPerformed(evt);
            }
        });
        jPanelChoixMenu.add(jCheckBoxEurope);
        jCheckBoxEurope.setBounds(220, 520, 100, 23);

        jCheckBoxAmeriqueDuNord.setText("Amerique du Nord");
        jPanelChoixMenu.add(jCheckBoxAmeriqueDuNord);
        jCheckBoxAmeriqueDuNord.setBounds(330, 520, 160, 23);

        jCheckBoxAmeriqueDuSud.setText("Amerique du Sud");
        jPanelChoixMenu.add(jCheckBoxAmeriqueDuSud);
        jCheckBoxAmeriqueDuSud.setBounds(510, 520, 140, 23);

        jCheckBoxAsie.setText("Asie");
        jPanelChoixMenu.add(jCheckBoxAsie);
        jCheckBoxAsie.setBounds(230, 570, 80, 23);

        jCheckBoxAfrique.setText("Afrique");
        jPanelChoixMenu.add(jCheckBoxAfrique);
        jCheckBoxAfrique.setBounds(330, 570, 100, 23);

        jCheckBoxOceanie.setText("Océanie");
        jPanelChoixMenu.add(jCheckBoxOceanie);
        jCheckBoxOceanie.setBounds(450, 570, 100, 23);

        jCheckBonus.setText("Bonus");
        jPanelChoixMenu.add(jCheckBonus);
        jCheckBonus.setBounds(570, 430, 81, 23);

        jCheckBoxAntartique.setText("Antartique");
        jPanelChoixMenu.add(jCheckBoxAntartique);
        jCheckBoxAntartique.setBounds(560, 570, 120, 23);

        jRadioButtonContreLaMontre.setText("Contre la montre");
        jPanelChoixMenu.add(jRadioButtonContreLaMontre);
        jRadioButtonContreLaMontre.setBounds(310, 250, 140, 23);

        jRadioButtonDuo.setText("Duo");
        jPanelChoixMenu.add(jRadioButtonDuo);
        jRadioButtonDuo.setBounds(230, 420, 100, 23);

        jRadioButtonCarre.setText("Carré");
        jRadioButtonCarre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCarreActionPerformed(evt);
            }
        });
        jPanelChoixMenu.add(jRadioButtonCarre);
        jRadioButtonCarre.setBounds(340, 420, 100, 23);

        jRadioButtonCash.setText("Cash");
        jPanelChoixMenu.add(jRadioButtonCash);
        jRadioButtonCash.setBounds(460, 420, 100, 23);

        jRadioButtonEntrainement.setText("Entrainement");
        jPanelChoixMenu.add(jRadioButtonEntrainement);
        jRadioButtonEntrainement.setBounds(550, 40, 150, 23);

        jLabelModeReponse.setText("Mode de réponse");
        jPanelChoixMenu.add(jLabelModeReponse);
        jLabelModeReponse.setBounds(420, 400, 130, 14);

        jRadioButtonCompetition.setText("Compétition");
        jPanelChoixMenu.add(jRadioButtonCompetition);
        jRadioButtonCompetition.setBounds(260, 40, 140, 23);

        jButtonFeedback.setText("Feedback");
        jPanelChoixMenu.add(jButtonFeedback);
        jButtonFeedback.setBounds(10, 100, 140, 23);

        jButtonCroissante.setText("Croissante");
        jPanelChoixMenu.add(jButtonCroissante);
        jButtonCroissante.setBounds(470, 360, 100, 23);

        jButtonImpossible.setText("Impossible");
        jButtonImpossible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImpossibleActionPerformed(evt);
            }
        });
        jPanelChoixMenu.add(jButtonImpossible);
        jButtonImpossible.setBounds(330, 360, 120, 23);

        jButtonBestScores.setText("Meilleurs scores");
        jPanelChoixMenu.add(jButtonBestScores);
        jButtonBestScores.setBounds(10, 40, 140, 23);

        jButtonSimilaire.setText("Similaire");
        jPanelChoixMenu.add(jButtonSimilaire);
        jButtonSimilaire.setBounds(730, 360, 71, 23);

        jRadioButtonSprint.setText("Le sprint");
        jPanelChoixMenu.add(jRadioButtonSprint);
        jRadioButtonSprint.setBounds(690, 250, 67, 23);

        jButtonDeconnexion.setText("Déconnexion");
        jPanelChoixMenu.add(jButtonDeconnexion);
        jButtonDeconnexion.setBounds(10, 70, 140, 23);

        jRadioButtonMonde.setText("Monde");
        jPanelChoixMenu.add(jRadioButtonMonde);
        jRadioButtonMonde.setBounds(530, 480, 120, 23);

        jButtonUltra.setText("Ultra");
        jButtonUltra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltraActionPerformed(evt);
            }
        });
        jPanelChoixMenu.add(jButtonUltra);
        jButtonUltra.setBounds(620, 320, 120, 23);

        jButtonProfil.setText("Mon profil");
        jPanelChoixMenu.add(jButtonProfil);
        jButtonProfil.setBounds(10, 130, 140, 23);

        jButtonPiege.setText("Piège");
        jPanelChoixMenu.add(jButtonPiege);
        jButtonPiege.setBounds(580, 360, 70, 23);

        jButtonQuitter.setText("Quitter");
        jPanelChoixMenu.add(jButtonQuitter);
        jButtonQuitter.setBounds(740, 580, 67, 23);

        jButtonSubtile.setText("Subtile");
        jPanelChoixMenu.add(jButtonSubtile);
        jButtonSubtile.setBounds(660, 360, 65, 23);
        jPanelChoixMenu.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 830, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelChoixMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelChoixMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxEuropeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEuropeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEuropeActionPerformed

    private void jRadioButtonCarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCarreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCarreActionPerformed

    private void jButtonImpossibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImpossibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImpossibleActionPerformed

    private void jButtonUltraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUltraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueMenuChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueMenuChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueMenuChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueMenuChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueMenuChoix().setVisible(true);
            }
        });
    }

    public JButton getjButtonDifficile() {
        return jButtonDifficile;
    }

    public JButton getjButtonExpert() {
        return jButtonExpert;
    }

    public JButton getjButtonFacile() {
        return jButtonFacile;
    }

    public JButton getjButtonMoyen() {
        return jButtonMoyen;
    }

    public JButton getjButtonOptions() {
        return jButtonOptions;
    }

    public JLabel getjLabelBackground() {
        return jLabelBackground;
    }

    public JLabel getjLabelDifficulte() {
        return jLabelDifficulte;
    }

    public JLabel getjLabelTheme() {
        return jLabelTheme;
    }

    public JLabel getjLabelTitre() {
        return jLabelTitre;
    }

    public JPanel getjPanelChoixMenu() {
        return jPanelChoixMenu;
    }

    public JRadioButton getjRadioButtonCapitale() {
        return jRadioButtonCapitale;
    }

    public JRadioButton getjRadioButtonClassique() {
        return jRadioButtonClassique;
    }

    public JRadioButton getjRadioButtonContinent() {
        return jRadioButtonContinent;
    }

    public JRadioButton getjRadioButtonDrapeau() {
        return jRadioButtonDrapeau;
    }

    public JRadioButton getjRadioButtonLangues() {
        return jRadioButtonLangues;
    }

    public JRadioButton getjRadioButtonLieux() {
        return jRadioButtonLieux;
    }

    public JRadioButton getjRadioButtonLocalisation() {
        return jRadioButtonLocalisation;
    }

    public JRadioButton getjRadioButtonPopulation() {
        return jRadioButtonPopulation;
    }

    public JRadioButton getjRadioButtonRapidite() {
        return jRadioButtonRapidite;
    }

    public JRadioButton getjRadioButtonSuperficie() {
        return jRadioButtonSuperficie;
    }

    public JRadioButton getjRadioButtonSurvie() {
        return jRadioButtonSurvie;
    }

    public JCheckBox getjCheckBoxInverse() {
        return jCheckBoxInverse;
    }

    public JLabel getjLabelMode() {
        return jLabelMode;
    }

    public JButton getjButtonImpossible() {
        return jButtonImpossible;
    }

    public JButton getjButtonStandard() {
        return jButtonStandard;
    }

    public JCheckBox getjCheckBonus() {
        return jCheckBonus;
    }

    public JCheckBox getjCheckBoxAfrique() {
        return jCheckBoxAfrique;
    }

    public JCheckBox getjCheckBoxAmeriqueDuNord() {
        return jCheckBoxAmeriqueDuNord;
    }

    public JCheckBox getjCheckBoxAmeriqueDuSud() {
        return jCheckBoxAmeriqueDuSud;
    }

    public JCheckBox getjCheckBoxAntartique() {
        return jCheckBoxAntartique;
    }

    public JCheckBox getjCheckBoxAsie() {
        return jCheckBoxAsie;
    }

    public JCheckBox getjCheckBoxEurope() {
        return jCheckBoxEurope;
    }

    public JCheckBox getjCheckBoxOceanie() {
        return jCheckBoxOceanie;
    }

    public JLabel getjLabelContinent() {
        return jLabelContinent;
    }

    public JRadioButton getjRadioButtonFormes() {
        return jRadioButtonFormes;
    }

    public JRadioButton getjRadioButtonContreLaMontre() {
        return jRadioButtonContreLaMontre;
    }

    public JButton getjButtonBestScores() {
        return jButtonBestScores;
    }

    public JButton getjButtonCroissante() {
        return jButtonCroissante;
    }

    public JButton getjButtonDeconnexion() {
        return jButtonDeconnexion;
    }

    public JLabel getjLabelModeReponse() {
        return jLabelModeReponse;
    }

    public JRadioButton getjRadioButtonCarre() {
        return jRadioButtonCarre;
    }

    public JRadioButton getjRadioButtonCash() {
        return jRadioButtonCash;
    }

    public JRadioButton getjRadioButtonCompetition() {
        return jRadioButtonCompetition;
    }

    public JRadioButton getjRadioButtonDuo() {
        return jRadioButtonDuo;
    }

    public JRadioButton getjRadioButtonEntrainement() {
        return jRadioButtonEntrainement;
    }

    public JRadioButton getjRadioButtonMonde() {
        return jRadioButtonMonde;
    }

    public JButton getjButtonPiege() {
        return jButtonPiege;
    }

    public JButton getjButtonFeedback() {
        return jButtonFeedback;
    }

    public JButton getjButtonUltra() {
        return jButtonUltra;
    }

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public JButton getjButtonSubtile() {
        return jButtonSubtile;
    }

    public JButton getjButtonSimilaire() {
        return jButtonSimilaire;
    }

    public JRadioButton getjRadioButtonSprint() {
        return jRadioButtonSprint;
    }

    public JButton getjButtonProfil() {
        return jButtonProfil;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBestScores;
    private javax.swing.JButton jButtonCroissante;
    private javax.swing.JButton jButtonDeconnexion;
    private javax.swing.JButton jButtonDifficile;
    private javax.swing.JButton jButtonExpert;
    private javax.swing.JButton jButtonFacile;
    private javax.swing.JButton jButtonFeedback;
    private javax.swing.JButton jButtonImpossible;
    private javax.swing.JButton jButtonMoyen;
    private javax.swing.JButton jButtonOptions;
    private javax.swing.JButton jButtonPiege;
    private javax.swing.JButton jButtonProfil;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonSimilaire;
    private javax.swing.JButton jButtonStandard;
    private javax.swing.JButton jButtonSubtile;
    private javax.swing.JButton jButtonUltra;
    private javax.swing.JCheckBox jCheckBonus;
    private javax.swing.JCheckBox jCheckBoxAfrique;
    private javax.swing.JCheckBox jCheckBoxAmeriqueDuNord;
    private javax.swing.JCheckBox jCheckBoxAmeriqueDuSud;
    private javax.swing.JCheckBox jCheckBoxAntartique;
    private javax.swing.JCheckBox jCheckBoxAsie;
    private javax.swing.JCheckBox jCheckBoxEurope;
    private javax.swing.JCheckBox jCheckBoxInverse;
    private javax.swing.JCheckBox jCheckBoxOceanie;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelContinent;
    private javax.swing.JLabel jLabelDifficulte;
    private javax.swing.JLabel jLabelMode;
    private javax.swing.JLabel jLabelModeReponse;
    private javax.swing.JLabel jLabelTheme;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanelChoixMenu;
    private javax.swing.JRadioButton jRadioButtonCapitale;
    private javax.swing.JRadioButton jRadioButtonCarre;
    private javax.swing.JRadioButton jRadioButtonCash;
    private javax.swing.JRadioButton jRadioButtonClassique;
    private javax.swing.JRadioButton jRadioButtonCompetition;
    private javax.swing.JRadioButton jRadioButtonContinent;
    private javax.swing.JRadioButton jRadioButtonContreLaMontre;
    private javax.swing.JRadioButton jRadioButtonDrapeau;
    private javax.swing.JRadioButton jRadioButtonDuo;
    private javax.swing.JRadioButton jRadioButtonEntrainement;
    private javax.swing.JRadioButton jRadioButtonFormes;
    private javax.swing.JRadioButton jRadioButtonLangues;
    private javax.swing.JRadioButton jRadioButtonLieux;
    private javax.swing.JRadioButton jRadioButtonLocalisation;
    private javax.swing.JRadioButton jRadioButtonMonde;
    private javax.swing.JRadioButton jRadioButtonPopulation;
    private javax.swing.JRadioButton jRadioButtonRapidite;
    private javax.swing.JRadioButton jRadioButtonSprint;
    private javax.swing.JRadioButton jRadioButtonSuperficie;
    private javax.swing.JRadioButton jRadioButtonSurvie;
    // End of variables declaration//GEN-END:variables
}
