/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author lucas
 */
public class VueProfesseur extends javax.swing.JFrame {

    /**
     * Creates new form VueProfesseur
     */
    public VueProfesseur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jButtonScores = new javax.swing.JButton();
        jButtonGestion = new javax.swing.JButton();
        jComboBoxEleve = new javax.swing.JComboBox();
        jButtonRechercher = new javax.swing.JButton();
        jButtonJouer = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jButtonDeconnexion = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitre.setText("Bienvenue dans l'interface professeur");
        jPanel1.add(jLabelTitre);
        jLabelTitre.setBounds(240, 30, 293, 22);

        jButtonScores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonScores.setText("Consulter les scores");
        jButtonScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScoresActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonScores);
        jButtonScores.setBounds(130, 110, 200, 60);

        jButtonGestion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGestion.setText("Gestion Base De Données");
        jButtonGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGestion);
        jButtonGestion.setBounds(410, 230, 200, 60);

        jComboBoxEleve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxEleve);
        jComboBoxEleve.setBounds(410, 110, 200, 20);

        jButtonRechercher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRechercher.setText("Rechercher les scores");
        jPanel1.add(jButtonRechercher);
        jButtonRechercher.setBounds(410, 140, 200, 30);

        jButtonJouer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonJouer.setText("Jouer");
        jButtonJouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJouerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJouer);
        jButtonJouer.setBounds(130, 230, 200, 60);

        jButtonQuitter.setText("Quitter");
        jPanel1.add(jButtonQuitter);
        jButtonQuitter.setBounds(620, 380, 90, 23);

        jButtonDeconnexion.setText("Deconnexion");
        jPanel1.add(jButtonDeconnexion);
        jButtonDeconnexion.setBounds(450, 380, 120, 23);
        jPanel1.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 740, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonScoresActionPerformed

    private void jButtonGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionActionPerformed

    private void jButtonJouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJouerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJouerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueProfesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueProfesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueProfesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueProfesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueProfesseur().setVisible(true);
            }
        });
    }

    public JButton getjButtonJouer() {
        return jButtonJouer;
    }

    public JButton getjButtonRechercher() {
        return jButtonRechercher;
    }

    public JButton getjButtonReinitialiser() {
        return jButtonGestion;
    }

    public JButton getjButtonScores() {
        return jButtonScores;
    }

    public JComboBox getjComboBoxEleve() {
        return jComboBoxEleve;
    }

    public JLabel getjLabelBackground() {
        return jLabelBackground;
    }

    public JLabel getjLabelTitre() {
        return jLabelTitre;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JButton getjButtonDeconnexion() {
        return jButtonDeconnexion;
    }

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public JButton getjButtonGestion() {
        return jButtonGestion;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeconnexion;
    private javax.swing.JButton jButtonGestion;
    private javax.swing.JButton jButtonJouer;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRechercher;
    private javax.swing.JButton jButtonScores;
    private javax.swing.JComboBox jComboBoxEleve;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
