/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JToggleButton;

/**
 *
 * @author lucas
 */
public class VueScoreEleve extends javax.swing.JFrame {

    /**
     * Creates new form VueScoreEleve
     */
    public VueScoreEleve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableScores = new javax.swing.JTable();
        jButtonRechercher = new javax.swing.JButton();
        jComboBoxEleve = new javax.swing.JComboBox();
        jButtonQuitter = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitre.setText("Scores Individuels");
        jPanel1.add(jLabelTitre);
        jLabelTitre.setBounds(280, 20, 180, 22);

        jTableScores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableScores);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(62, 110, 570, 230);

        jButtonRechercher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRechercher.setText("Rechercher les scores");
        jPanel1.add(jButtonRechercher);
        jButtonRechercher.setBounds(360, 70, 200, 30);

        jComboBoxEleve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxEleve);
        jComboBoxEleve.setBounds(130, 70, 200, 30);

        jButtonQuitter.setText("Quitter");
        jPanel1.add(jButtonQuitter);
        jButtonQuitter.setBounds(620, 370, 67, 23);

        jButtonRetour.setText("Retour");
        jPanel1.add(jButtonRetour);
        jButtonRetour.setBounds(510, 370, 65, 23);
        jPanel1.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 720, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueScoreEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueScoreEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueScoreEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueScoreEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueScoreEleve().setVisible(true);
            }
        });
    }

    public JButton getjButtonRechercher() {
        return jButtonRechercher;
    }

    public JComboBox getjComboBoxEleve() {
        return jComboBoxEleve;
    }

    public JLabel getjLabelBackground() {
        return jLabelBackground;
    }

    public JLabel getjLabelTitre() {
        return jLabelTitre;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getjTableScores() {
        return jTableScores;
    }

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public JButton getjButtonRetour() {
        return jButtonRetour;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRechercher;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JComboBox jComboBoxEleve;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableScores;
    // End of variables declaration//GEN-END:variables
}
