/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Benoit
 */
public class VueScoreChoix extends javax.swing.JFrame {

    /**
     * Creates new form VueScoreChoix
     */
    public VueScoreChoix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScoreChoix = new javax.swing.JPanel();
        jRadioButtonCapitale = new javax.swing.JRadioButton();
        jRadioButtonClassique = new javax.swing.JRadioButton();
        jRadioButtonContreLaMontre = new javax.swing.JRadioButton();
        jRadioButtonRapidite = new javax.swing.JRadioButton();
        jRadioButtonSurvie = new javax.swing.JRadioButton();
        jRadioButtonFacile = new javax.swing.JRadioButton();
        jRadioButtonMoyen = new javax.swing.JRadioButton();
        jRadioButtonDifficile = new javax.swing.JRadioButton();
        jLabelTheme = new javax.swing.JLabel();
        jLabelMode = new javax.swing.JLabel();
        jLabelDifficulte = new javax.swing.JLabel();
        jRadioButtonExpert = new javax.swing.JRadioButton();
        jRadioButtonDrapeau = new javax.swing.JRadioButton();
        jLabelTitre = new javax.swing.JLabel();
        jButtonQuitter = new javax.swing.JButton();
        jButtonMenuPrincipal = new javax.swing.JButton();
        jButtonAfficher = new javax.swing.JButton();
        jLabelScoreChoix = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Voir les socres");

        jPanelScoreChoix.setLayout(null);

        jRadioButtonCapitale.setText("Capitale");
        jPanelScoreChoix.add(jRadioButtonCapitale);
        jRadioButtonCapitale.setBounds(120, 90, 110, 23);

        jRadioButtonClassique.setText("Classique");
        jPanelScoreChoix.add(jRadioButtonClassique);
        jRadioButtonClassique.setBounds(120, 160, 120, 23);

        jRadioButtonContreLaMontre.setText("Contre la montre");
        jPanelScoreChoix.add(jRadioButtonContreLaMontre);
        jRadioButtonContreLaMontre.setBounds(250, 160, 130, 23);

        jRadioButtonRapidite.setText("Rapidité");
        jRadioButtonRapidite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRapiditeActionPerformed(evt);
            }
        });
        jPanelScoreChoix.add(jRadioButtonRapidite);
        jRadioButtonRapidite.setBounds(400, 160, 140, 23);

        jRadioButtonSurvie.setText("Survie");
        jPanelScoreChoix.add(jRadioButtonSurvie);
        jRadioButtonSurvie.setBounds(550, 160, 110, 23);

        jRadioButtonFacile.setText("Facile");
        jPanelScoreChoix.add(jRadioButtonFacile);
        jRadioButtonFacile.setBounds(120, 230, 110, 23);

        jRadioButtonMoyen.setText("Moyen");
        jPanelScoreChoix.add(jRadioButtonMoyen);
        jRadioButtonMoyen.setBounds(250, 230, 100, 23);

        jRadioButtonDifficile.setText("Difficile");
        jPanelScoreChoix.add(jRadioButtonDifficile);
        jRadioButtonDifficile.setBounds(400, 230, 130, 23);

        jLabelTheme.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelTheme.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTheme.setText("Thème");
        jPanelScoreChoix.add(jLabelTheme);
        jLabelTheme.setBounds(120, 54, 100, 30);

        jLabelMode.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelMode.setForeground(new java.awt.Color(0, 0, 204));
        jLabelMode.setText("Mode");
        jPanelScoreChoix.add(jLabelMode);
        jLabelMode.setBounds(120, 124, 100, 30);

        jLabelDifficulte.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelDifficulte.setForeground(new java.awt.Color(0, 51, 153));
        jLabelDifficulte.setText("Difficulté");
        jPanelScoreChoix.add(jLabelDifficulte);
        jLabelDifficulte.setBounds(120, 194, 160, 30);

        jRadioButtonExpert.setText("Expert");
        jPanelScoreChoix.add(jRadioButtonExpert);
        jRadioButtonExpert.setBounds(550, 230, 110, 23);

        jRadioButtonDrapeau.setText("Drapeau");
        jPanelScoreChoix.add(jRadioButtonDrapeau);
        jRadioButtonDrapeau.setBounds(250, 90, 93, 23);

        jLabelTitre.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(204, 0, 0));
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Voir les scores");
        jPanelScoreChoix.add(jLabelTitre);
        jLabelTitre.setBounds(0, 0, 720, 50);

        jButtonQuitter.setText("Quitter");
        jPanelScoreChoix.add(jButtonQuitter);
        jButtonQuitter.setBounds(573, 460, 130, 23);

        jButtonMenuPrincipal.setText("Menu Principal");
        jPanelScoreChoix.add(jButtonMenuPrincipal);
        jButtonMenuPrincipal.setBounds(10, 460, 140, 23);

        jButtonAfficher.setText("Afficher");
        jButtonAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherActionPerformed(evt);
            }
        });
        jPanelScoreChoix.add(jButtonAfficher);
        jButtonAfficher.setBounds(310, 320, 120, 23);
        jPanelScoreChoix.add(jLabelScoreChoix);
        jLabelScoreChoix.setBounds(0, 0, 720, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelScoreChoix, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelScoreChoix, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonRapiditeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRapiditeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRapiditeActionPerformed

    private void jButtonAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueScoreChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueScoreChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueScoreChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueScoreChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueScoreChoix().setVisible(true);
            }
        });
    }

    public JButton getjButtonAfficher() {
        return jButtonAfficher;
    }

    public JLabel getjLabelDifficulte() {
        return jLabelDifficulte;
    }

    public JLabel getjLabelMode() {
        return jLabelMode;
    }

    public JLabel getjLabelScoreChoix() {
        return jLabelScoreChoix;
    }

    public JLabel getjLabelTheme() {
        return jLabelTheme;
    }

    public JLabel getjLabelTitre() {
        return jLabelTitre;
    }

    public JPanel getjPanelScoreChoix() {
        return jPanelScoreChoix;
    }

    public JRadioButton getjRadioButtonCapitale() {
        return jRadioButtonCapitale;
    }

    public JRadioButton getjRadioButtonClassique() {
        return jRadioButtonClassique;
    }

    public JRadioButton getjRadioButtonContreLaMontre() {
        return jRadioButtonContreLaMontre;
    }

    public JRadioButton getjRadioButtonDifficile() {
        return jRadioButtonDifficile;
    }

    public JRadioButton getjRadioButtonExpert() {
        return jRadioButtonExpert;
    }

    public JRadioButton getjRadioButtonFacile() {
        return jRadioButtonFacile;
    }

    public JRadioButton getjRadioButtonMoyen() {
        return jRadioButtonMoyen;
    }

    public JRadioButton getjRadioButtonRapidite() {
        return jRadioButtonRapidite;
    }

    public JRadioButton getjRadioButtonSurvie() {
        return jRadioButtonSurvie;
    }

    public JButton getjButtonMenuPrincipal() {
        return jButtonMenuPrincipal;
    }

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public JRadioButton getjRadioButtonDrapeau() {
        return jRadioButtonDrapeau;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JButton jButtonMenuPrincipal;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JLabel jLabelDifficulte;
    private javax.swing.JLabel jLabelMode;
    private javax.swing.JLabel jLabelScoreChoix;
    private javax.swing.JLabel jLabelTheme;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanelScoreChoix;
    private javax.swing.JRadioButton jRadioButtonCapitale;
    private javax.swing.JRadioButton jRadioButtonClassique;
    private javax.swing.JRadioButton jRadioButtonContreLaMontre;
    private javax.swing.JRadioButton jRadioButtonDifficile;
    private javax.swing.JRadioButton jRadioButtonDrapeau;
    private javax.swing.JRadioButton jRadioButtonExpert;
    private javax.swing.JRadioButton jRadioButtonFacile;
    private javax.swing.JRadioButton jRadioButtonMoyen;
    private javax.swing.JRadioButton jRadioButtonRapidite;
    private javax.swing.JRadioButton jRadioButtonSurvie;
    // End of variables declaration//GEN-END:variables
}
