/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Benoit
 */
public class VueScores extends javax.swing.JFrame {

    /**
     * Creates new form VueScores
     */
    public VueScores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelClassement = new javax.swing.JPanel();
        jButtonRafraichir = new javax.swing.JButton();
        jLabelTitre = new javax.swing.JLabel();
        jScrollPaneScores = new javax.swing.JScrollPane();
        jTableScores = new javax.swing.JTable();
        jButtonMenu = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jLabelScore1 = new javax.swing.JLabel();
        jLabelFirst = new javax.swing.JLabel();
        jLabelScore2 = new javax.swing.JLabel();
        jLabelSecond = new javax.swing.JLabel();
        jLabelScore3 = new javax.swing.JLabel();
        jLabelThird = new javax.swing.JLabel();
        jLabelClassement = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jButtonJouer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Classement");
        setResizable(false);

        jPanelClassement.setLayout(null);

        jButtonRafraichir.setText("Rafraichir");
        jPanelClassement.add(jButtonRafraichir);
        jButtonRafraichir.setBounds(540, 50, 110, 23);

        jLabelTitre.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(255, 51, 0));
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Nos Globetrotters");
        jPanelClassement.add(jLabelTitre);
        jLabelTitre.setBounds(1, 10, 660, 30);

        jTableScores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneScores.setViewportView(jTableScores);

        jPanelClassement.add(jScrollPaneScores);
        jScrollPaneScores.setBounds(140, 270, 410, 200);

        jButtonMenu.setText("Menu Principal");
        jPanelClassement.add(jButtonMenu);
        jButtonMenu.setBounds(10, 520, 101, 30);

        jButtonQuitter.setText("Quitter");
        jPanelClassement.add(jButtonQuitter);
        jButtonQuitter.setBounds(560, 530, 90, 30);

        jLabelScore1.setText("Score1");
        jPanelClassement.add(jLabelScore1);
        jLabelScore1.setBounds(360, 120, 50, 20);

        jLabelFirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFirst.setText("First");
        jPanelClassement.add(jLabelFirst);
        jLabelFirst.setBounds(220, 120, 130, 20);

        jLabelScore2.setText("Score2");
        jPanelClassement.add(jLabelScore2);
        jLabelScore2.setBounds(190, 180, 50, 20);

        jLabelSecond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSecond.setText("Second");
        jPanelClassement.add(jLabelSecond);
        jLabelSecond.setBounds(50, 180, 130, 20);

        jLabelScore3.setText("Score3");
        jPanelClassement.add(jLabelScore3);
        jLabelScore3.setBounds(530, 180, 50, 20);

        jLabelThird.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelThird.setText("First");
        jPanelClassement.add(jLabelThird);
        jLabelThird.setBounds(400, 180, 120, 20);

        jLabelClassement.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabelClassement.setForeground(new java.awt.Color(0, 0, 204));
        jLabelClassement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClassement.setText("details");
        jPanelClassement.add(jLabelClassement);
        jLabelClassement.setBounds(0, 480, 660, 20);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/podium.png"))); // NOI18N
        jPanelClassement.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 660, 490);

        jButtonJouer.setText("Jouer");
        jPanelClassement.add(jButtonJouer);
        jButtonJouer.setBounds(273, 513, 90, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClassement, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClassement, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueScores().setVisible(true);
            }
        });
    }

    public JTable getjTableScores() {
        return jTableScores;
    }

    public JLabel getjLabelBackground() {
        return jLabelBackground;
    }

    public JButton getjButtonMenu() {
        return jButtonMenu;
    }

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public JLabel getjLabelFirst() {
        return jLabelFirst;
    }

    public JLabel getjLabelScore1() {
        return jLabelScore1;
    }

    public JLabel getjLabelScore2() {
        return jLabelScore2;
    }

    public JLabel getjLabelScore3() {
        return jLabelScore3;
    }

    public JLabel getjLabelSecond() {
        return jLabelSecond;
    }

    public JLabel getjLabelThird() {
        return jLabelThird;
    }

    public JLabel getjLabelTitre() {
        return jLabelTitre;
    }

    public JPanel getjPanelClassement() {
        return jPanelClassement;
    }

    public JScrollPane getjScrollPaneScores() {
        return jScrollPaneScores;
    }

    public JLabel getjLabelClassement() {
        return jLabelClassement;
    }

    public JButton getjButtonJouer() {
        return jButtonJouer;
    }

    public JButton getjButtonRafraichir() {
        return jButtonRafraichir;
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJouer;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRafraichir;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelClassement;
    private javax.swing.JLabel jLabelFirst;
    private javax.swing.JLabel jLabelScore1;
    private javax.swing.JLabel jLabelScore2;
    private javax.swing.JLabel jLabelScore3;
    private javax.swing.JLabel jLabelSecond;
    private javax.swing.JLabel jLabelThird;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanelClassement;
    private javax.swing.JScrollPane jScrollPaneScores;
    private javax.swing.JTable jTableScores;
    // End of variables declaration//GEN-END:variables
}
